import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';
import Provider from '@/providers/Provider';
import { Toaster } from 'sonner';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'VaultChain',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<Provider>
				<body
					className={`${inter.className} dark:bg-mybackground-dark bg-mybackground-light dark:text-mybackground-light text-mybackground-dark scroll-smooth flex flex-col min-h-screen `}>
					<Navbar />
					<div className=''>{children}</div>
					<Toaster />
				</body>
			</Provider>
		</html>
	);
}
